export { default as Navbar } from './Navbar/Navbar';
export { default as Footer } from './Footer/Footer';
export { default as InfoSection } from './InfoSection/InfoSection';
export { default as Signup } from './Signup/Signup';
export { default as Login } from './Login/Login';
export { default as OurStory } from './OurStory/OurStory';
export { default as Upload } from './Upload/Upload';
export { default as VideoSection } from './VideoSection/VideoSection';
export { default as Feedback } from './Feedback/Feedback';